// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"github.com/cca/go-indexer/internal/domain/cca"
)

type AuctionConnection struct {
	Edges    []*AuctionEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type AuctionEdge struct {
	Node   *cca.Auction `json:"node"`
	Cursor string       `json:"cursor"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Query struct {
}
