package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"math/big"
	"strings"

	"github.com/cca/go-indexer/internal/api/pagination"
	"github.com/cca/go-indexer/internal/domain/cca"
	"github.com/cca/go-indexer/internal/store"
	"github.com/ethereum/go-ethereum/common"
)

// StartBlock is the resolver for the startBlock field.
func (r *auctionResolver) StartBlock(ctx context.Context, obj *cca.Auction) (int, error) {
	return int(obj.StartBlock), nil
}

// EndBlock is the resolver for the endBlock field.
func (r *auctionResolver) EndBlock(ctx context.Context, obj *cca.Auction) (int, error) {
	return int(obj.EndBlock), nil
}

// ClaimBlock is the resolver for the claimBlock field.
func (r *auctionResolver) ClaimBlock(ctx context.Context, obj *cca.Auction) (int, error) {
	return int(obj.ClaimBlock), nil
}

// ClearingPriceQ96 is the resolver for the clearingPriceQ96 field.
func (r *auctionResolver) ClearingPriceQ96(ctx context.Context, obj *cca.Auction) (*big.Int, error) {
	addr := strings.ToLower(obj.AuctionAddress.Hex())
	cp, err := r.Store.CheckpointRepo().GetLatest(ctx, r.ChainID, addr)
	if err != nil {
		return nil, err
	}
	if cp == nil {
		return nil, nil
	}
	return cp.ClearingPriceQ96, nil
}

// Auction is the resolver for the auction field.
func (r *queryResolver) Auction(ctx context.Context, address common.Address) (*cca.Auction, error) {
	addr := strings.ToLower(address.Hex())
	return r.Store.AuctionRepo().GetByAddress(ctx, r.ChainID, addr)
}

// Auctions is the resolver for the auctions field.
func (r *queryResolver) Auctions(ctx context.Context, chainID *int, first *int, after *string) (*AuctionConnection, error) {
	cid := r.ChainID
	if chainID != nil {
		cid = int64(*chainID)
	}

	limit := pagination.DefaultLimit
	if first != nil {
		limit = pagination.ClampLimit(*first)
	}

	params := store.PaginationParams{
		Limit: limit + 1, // N+1 fetch to detect next page
	}

	if after != nil {
		blockNumber, logIndex, err := pagination.DecodeCursor(*after)
		if err != nil {
			return nil, err
		}
		params.CursorBlockNumber = &blockNumber
		params.CursorLogIndex = &logIndex
	}

	auctions, err := r.Store.AuctionRepo().List(ctx, cid, params)
	if err != nil {
		return nil, err
	}

	hasNext := len(auctions) > limit
	if hasNext {
		auctions = auctions[:limit]
	}

	edges := make([]*AuctionEdge, len(auctions))
	for i, a := range auctions {
		edges[i] = &AuctionEdge{
			Node:   a,
			Cursor: pagination.EncodeCursor(a.BlockNumber, a.LogIndex),
		}
	}

	var endCursor *string
	if len(edges) > 0 {
		endCursor = &edges[len(edges)-1].Cursor
	}

	return &AuctionConnection{
		Edges: edges,
		PageInfo: &PageInfo{
			HasNextPage: hasNext,
			EndCursor:   endCursor,
		},
	}, nil
}

// Auction returns AuctionResolver implementation.
func (r *Resolver) Auction() AuctionResolver { return &auctionResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type auctionResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
